In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [2]:
transactions = []

with open("Datasets/groceries.csv","r") as f:
    for line in f:
        items = line.strip().split(",")
        transactions.append(items)

In [3]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions,sparse=True)
df = pd.DataFrame.sparse.from_spmatrix(te_array,columns=te.columns_)
df

C:\Users\navde\AppData\Local\Temp\ipykernel_3464\3916823536.py:3: FutureWarning: Allowing arbitrary scalar fill_value in SparseDtype is deprecated. In a future version, the fill_value must be a valid value for the SparseDtype.subtype.
  df = pd.DataFrame.sparse.from_spmatrix(te_array,columns=te.columns_)

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
9831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9832,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9833,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9834,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [4]:
# Apriori ->

freq_items = apriori(df, min_support = 0.02, use_colnames = True)
freq_items

      support                                         itemsets
0    0.033452                                       (UHT-milk)
1    0.052466                                           (beef)
2    0.033249                                        (berries)
3    0.026029                                      (beverages)
4    0.080529                                   (bottled beer)
..        ...                                              ...
117  0.032232                 (whole milk, whipped/sour cream)
118  0.020742                     (yogurt, whipped/sour cream)
119  0.056024                             (yogurt, whole milk)
120  0.023183  (whole milk, root vegetables, other vegetables)
121  0.022267           (yogurt, whole milk, other vegetables)

[122 rows x 2 columns]

In [5]:
# Association rules

rules = association_rules(freq_items, metric = 'confidence', min_threshold = 0.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,1.0,0.007845,1.251315,0.389597,0.074113,0.200841,0.244103
1,(bottled beer),(whole milk),0.080529,0.255516,0.020437,0.253788,0.993237,1.0,-0.000139,0.997684,-0.007351,0.064755,-0.002321,0.166886
2,(bottled water),(other vegetables),0.110524,0.193493,0.024809,0.224471,1.160101,1.0,0.003424,1.039945,0.155154,0.088857,0.038411,0.176345
3,(bottled water),(rolls/buns),0.110524,0.183935,0.024199,0.218951,1.190373,1.0,0.003870,1.044832,0.179800,0.089541,0.042909,0.175258
4,(bottled water),(soda),0.110524,0.174377,0.028978,0.262190,1.503577,1.0,0.009705,1.119017,0.376535,0.113230,0.106359,0.214185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,"(root vegetables, other vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,1.0,0.011076,1.457687,0.501524,0.082879,0.313982,0.289999
69,(root vegetables),"(whole milk, other vegetables)",0.108998,0.074835,0.023183,0.212687,2.842082,1.0,0.015026,1.175091,0.727435,0.144304,0.149002,0.261235
70,"(yogurt, whole milk)",(other vegetables),0.056024,0.193493,0.022267,0.397459,2.054131,1.0,0.011427,1.338511,0.543633,0.097987,0.252901,0.256270
71,"(yogurt, other vegetables)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,1.0,0.011174,1.528340,0.524577,0.080485,0.345695,0.300014
72,"(whole milk, other vegetables)",(yogurt),0.074835,0.139502,0.022267,0.297554,2.132979,1.0,0.011828,1.225003,0.574138,0.115934,0.183676,0.228588

In [6]:
rules = rules[
    (rules['lift'] > 1) &
    (rules['confidence'] >= 0.6)
]

# Sort rules by lift
rules = rules.sort_values(by='lift', ascending=False)

print("\nAssociation Rules:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

Association Rules:
Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []